### ISSUE TITLE
Add a nominative scoreboard

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/qotd#54]
As we elect Quote of day (:3rd_place_medal:), Quote of the month (:2nd_place_medal:) and Quote of the Year (:1st_place_medal:) we could have a nominative score ladder too.

Something like this:

![image](https://github.com/jolicode/qotd/assets/225704/5583a67e-d417-4272-9193-5f946542d5c0)

**Comment by damienalexandre** [comment]
- User gets a :3rd_place_medal: for each QOTD
- When this QOTD is QOTM, :3rd_place_medal: become :2nd_place_medal: (must be months in the past only)
- When this QOTD is QOTY, :2nd_place_medal: become :1st_place_medal: (must be year in the past only)

**Comment by lyrixx** [comment]
Fixed by https://github.com/jolicode/qotd/pull/67

Was definitively not a "good first issue" 😅
